name: backend

on: [push]

jobs:
  build:
    env:
      DATABASE_URL: postgres://red_drink:red_drink@localhost:5432/red_drink
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: red_drink
          POSTGRES_PASSWORD: red_drink
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - name: Create .env
        run: |
          cd ./backend
          echo "DATABASE_URL=localhost" >> .env
      - name: Build server
        run: |
          cd ./backend
          cargo build --bin red_drink --verbose
      - name: Build tool `hua`
        run: |
          cd ./backend
          cargo build --bin hua --verbose
      - name: Build tool `add_role_to_user`
        run: |
          cd ./backend
          cargo build --bin add_role_to_user --verbose
      - name: Setup database
        run: |
          cd ./backend
          cargo install diesel_cli --no-default-features --features postgres
          diesel setup
          diesel migration run
      - name: Test server
        run: |
          cd ./backend
          cargo test --bin red_drink --verbose
      - name: Test tool `create_user`
        run: |
          cd ./backend
          cargo test --bin create_user --verbose
      - name: Test tool `add_role_to_user`
        run: |
          cd ./backend
          cargo test --bin add_role_to_user --verbose