name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        cd ./backend
        export DATABASE_URL=postgres://root:root@localhost:5432/red_drink
        export RED_DRINK_GITHUB_CLIENT_ID=github_client_id
        export RED_DRINK_GITHUB_CLIENT_SECRET=github_client_secret
        export RED_DRINK_GITHUB_REDIRECT_URL=https://example.com/auth
    - name: Build server
      run: cargo build --bin red_drink --verbose
    - name: Build tool `create_user`
      run: cargo build --bin create_user --verbose
    - name: Build tool `add_role_to_user`
      run: cargo build --bin add_role_to_user --verbose
    - name: Test server
      run: cargo test --bin red_drink --verbose
    - name: Test tool `create_user`
      run: cargo test --bin create_user --verbose
    - name: Test tool `add_role_to_user`
      run: cargo test --bin add_role_to_user --verbose